; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
[platformio]
default_envs = serial_upload

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
build_flags =
  -I include
  -DCORE_DEBUG_LEVEL=5
  -D DEBUG_I2C_LOCK                         ; Debug I2C-Lock
  -D DISABLE_IMAP
  -D DISABLE_FLASH 
  -D DISABLE_SD
  -D DISABLE_NTP_TIME
  -D SILENT_MODE
  -D BOARD_HAS_PSRAM
  -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000    ; Timeout für TCP-Verbindung (Standard)
  -D CONFIG_ASYNC_TCP_PRIORITY=10          ; Priorität (Standard)
  -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64        ; Warteschlangengröße (Standard)
  -D CONFIG_ASYNC_TCP_RUNNING_CORE=1       ; Führe AsyncTCP auf Core 1 (Arduino-Core) aus
  -D CONFIG_ASYNC_TCP_STACK_SIZE=4096      ; Reduziere Stack-Größe auf 4K
  -D CONFIG_ESP32_ENABLE_COREDUMP=1        ; Aktiviere Core-Dump

lib_compat_mode = strict
lib_ldf_mode = chain
lib_extra_dirs =
    ${PROJECT_DIR}\..\include
    ${PROJECT_DIR}\..\lib

lib_deps =
	symlink://lib/ADS1115
	symlink://lib/MotorValve-master
	symlink://lib/PCF_Pump-master
    Arduino_DebugUtils @ 1.4.0
    paulstoffregen/Time @ 1.6
    br3ttb/PID @ 1.2.1
    adafruit/RTClib
    256dpi/MQTT @ ^2.4.8
    robtillaart/RunningMedian @ 0.3.9
    bblanchon/ArduinoJson @ 6.17.2
    milesburton/DallasTemperature @ 3.9.1
    marvinroger/AsyncMqttClient @ 0.9.0
    adafruit/Adafruit BME280 Library @ 2.2.2
    seithan/Easy Nextion Library @ 1.0.6
    ; PaulStoffregen/OneWire @ 2.3.8
    https://github.com/promillen/OneWire/archive/refs/heads/patch-1.zip ;Patch für ESP32-S3
    ESP32Async/AsyncTCP
  	ESP32Async/ESPAsyncWebServer
    ; mobizt/ESP Mail Client @ ^3.4.19

[env:serial_upload]
lib_deps = ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D DEVT
    -DCONFIG_HEAP_POISONING_COMPREHENSIVE
upload_protocol = esptool
upload_port = COM10
monitor_port = COM10
debug_tool = esp-builtin
build_type = debug
;debug_init_break = tbreak setup  ; Optional: Startet Debugger bei setup()

[env:OTA_upload]
lib_deps = ${env.lib_deps}
build_flags =
    ${env.build_flags}
upload_protocol = espota
upload_port = 192.168.178.156
upload_flags = 
    --port=8063
    --auth=Fgixy001